### ISSUE TITLE
Random failures of t/main.t

### ISSUE THREAD

**Issue by eserte** [alnewkirk/Data-Object-Immutable#1]
See
* http://matrix.cpantesters.org/?dist=Data-Object-Immutable%200.07
* http://analysis.cpantesters.org/reports_by_field?distv=Data-Object-Immutable-0.07;field=qr%3A%28Failed%20test\s%2B\S%2B.*%29

**Comment by alnewkirk** [comment]
Thanks for the report. I looked into this issue and I will push out a fix sometime this week.

**Comment by alnewkirk** [comment]
Thanks for the heads-up on this. This issue has been addressed.
